theme: jekyll-theme-cayman
title: Shivam Vats
description: Data Science Enthusiast | AWS Cloud Support Associate
github:
  linked_url: https://www.linkedin.com/in/shivam-vats-38285a160/
  Github_url: https://github.com/shivam360d
