theme: jekyll-theme-cayman
title: Shivam Vats
description: Data Science Enthusiast | AWS Cloud Support Associate
show_downloads: true
github:
  linkedin_url: https://www.linkedin.com/in/shivam-vats-38285a160/
  Github_url: https://github.com/shivam360d
  resume_url: https://raw.githubusercontent.com/shivam360d/ShivamVats/main/resume.pdf
